### PR TITLE
Add instructional video

### PR DESCRIPTION
**Pull request by timsully**
Gracias por el plugin, compadre!

### CODE REVIEW

**Comment by basiclines** [comment]
Thank you @timsully for making such a great tutorial for SuperTidy!

I'll prefer to use your video in a `Tutorials & related articles` rather than in a `Youtube Video` section. In this way we allow other contributors to also link the content they create with Super Tidy!

Please can you change your PR to address this?
Thank you again!

**Comment by timsully** [comment]
@basiclines I updated the readme to say `Tutorials & related articles`. Let me know if that is the desired approach!

**Comment by basiclines** [comment]
Rocks! Thanks @timsully for your contribution!

**Comment by timsully** [comment]
https://github.com/timsully/memes/blob/master/dance__01.gif

**Pull request merged**
